version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: camisetas_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tienda_camisetas
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - camisetas_net

volumes:
  db_data:

networks:
  camisetas_net:
